sudo: required

language: python
python:
  - "2.7"

services:
  - docker

# command to install dependencies
before_install:
  - docker-compose build
  - pip install coveralls

install:
  - docker-compose up -d

# command to run tests
script:
  - docker ps | grep flask_livereviews
  - docker ps | grep postgres_livereviews
  - docker ps | grep mongodb_livereviews
  - coverage run --source . testrunner.py ./tests

after_success:
  coveralls